version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres
    container_name: postgres_container
    env_file:
      - .env
    volumes:
     - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
