"""Add Reservation model

Revision ID: 34415a135e90
Revises: 9c6463b69ad4
Create Date: 2024-11-04 12:08:33.180466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34415a135e90"
down_revision: Union[str, None] = "9c6463b69ad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation",
        sa.Column("from_reserve", sa.DateTime(), nullable=True),
        sa.Column("to_reserve", sa.DateTime(), nullable=True),
        sa.Column("meetingroom_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meetingroom_id"],
            ["meetingroom.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservation")
    # ### end Alembic commands ###
