"""second migration

Revision ID: 9c6463b69ad4
Revises: d8d5eb725cfa
Create Date: 2024-11-03 15:09:40.007116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c6463b69ad4"
down_revision: Union[str, None] = "d8d5eb725cfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meetingroom", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetingroom", "description")
    # ### end Alembic commands ###
